[tool.pytest.ini_options]
pythonpath = ["source", "tests"]
filterwarnings = "ignore::DeprecationWarning"

[tool.isort]
line_length = 105
profile = "black"
skip_glob = "venv*"
skip_gitignore = true

[tool.black]
line-length = 105

[tool.ruff]
line-length = 105
select = ["ALL"]
ignore = ["T201", # Ignore prints.
    "D211", "D213", # Ignore formatting conflicts.
    "ANN101",       # Missing type annotation for 'self' in method
    "S311",         # Standard pseudo-random generators are not suitable for cryptographic purposes
    ]

[tool.ruff.per-file-ignores]
"tests/*" = ["ANN201",  # Return type annotation
    "S101",  # Assertion used
    ]


[tool.mypy]
ignore_missing_imports = true
